# 3.Chapter Data Wrangling

## 3.1 Creating a Data Frame

In [1]:
import pandas as pd
dataframe = pd.DataFrame()

## 3.2 Describing the Data

In [39]:
url = "http://tinyurl.com/titanic-csv"
df = pd.read_csv(url)
# show first two rows
print(df.head(10)) # also try tail(2) for last two rows

# show dimensions
print("Dimensions: {}".format(df.shape))

# show statistics
df.describe()

df.shape

                                            Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female
1                    Allison, Miss Helen Loraine    1st   2.00  female
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female
4                  Allison, Master Hudson Trevor    1st   0.92    male
5                             Anderson, Mr Harry    1st  47.00    male
6               Andrews, Miss Kornelia Theodosia    1st  63.00  female
7                         Andrews, Mr Thomas, jr    1st  39.00    male
8   Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female
9                         Artagaveytia, Mr Ramon    1st  71.00    male

   Survived  SexCode
0         1        1
1         0        1
2         0        0
3         0        1
4         1        0
5         1        0
6         1        1
7         0        0
8         1        1
9         0        0
Dimensions: (1313, 6)

(1313, 6)

## 3.3 Navigating DataFrames

In [4]:
# select the first row
print(df.iloc[0])

# select three rows
print(df.iloc[1:4])

# all rows up to and including the fourth row
print(df.iloc[:4])

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                   29
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object
                                            Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female

   Survived  SexCode
1         0        1
2         0        0
3         0        1
                                            Name PClass   Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.0  female
1                    Allison, Miss Helen Loraine    1st   2.0  female
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female

   Survived  SexCode
0         1        1
1         0        1
2         0        0
3         0        1

In [5]:
# set index
df = df.set_index(df['Name'])

# show row
df.loc['Allen, Miss Elisabeth Walton']

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                   29
Sex                               female
Survived                               1
SexCode                                1
Name: Allen, Miss Elisabeth Walton, dtype: object

## 3.4 Selecting Rows Based on Conditionals

In [6]:
# select top two rows where column 'sex' is 'female'
df[df['Sex'] == 'female']

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.0,female,0,1
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.0,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.0,female,1,1
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.0,female,1,1
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.0,female,1,1
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.0,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.0,female,1,1
"Bowen, Miss Grace Scott","Bowen, Miss Grace Scott",1st,45.0,female,1,1
"Bowerman, Miss Elsie Edith","Bowerman, Miss Elsie Edith",1st,22.0,female,1,1
"Brown, Mrs James Joseph (Margaret Molly"" Tobin)""","Brown, Mrs James Joseph (Margaret Molly"" Tobin)""",1st,44.0,female,1,1
"Brown, Mrs John Murray (Caroline Lane Lamson)","Brown, Mrs John Murray (Caroline Lane Lamson)",1st,59.0,female,1,1
"Bucknell, Mrs William Robert (Emma Eliza Ward)","Bucknell, Mrs William Robert (Emma Eliza Ward)",1st,60.0,female,1,1
"Candee, Mrs Edward (Helen Churchill Hungerford)","Candee, Mrs Edward (Helen Churchill Hungerford)",1st,53.0,female,1,1
"Cardeza, Mrs James Warburton Martinez (Charlotte Wardle Drake)","Cardeza, Mrs James Warburton Martinez (Charlot...",1st,58.0,female,1,1
"Carter, Mrs William Ernest (Lucile Polk)","Carter, Mrs William Ernest (Lucile Polk)",1st,36.0,female,1,1
"Carter, Miss Lucile Polk","Carter, Miss Lucile Polk",1st,14.0,female,1,1
"Cassebeer, Mrs Henry Arthur jr (Genevieve Fosdick)","Cassebeer, Mrs Henry Arthur jr (Genevieve Fosd...",1st,NaN,female,1,1
"Cavendish, Mrs Tyrell William Julia Florence Siegel","Cavendish, Mrs Tyrell William Julia Florence S...",1st,NaN,female,1,1
"Chaffee, Mrs Herbert Fuller (Carrie Constance Toogood)","Chaffee, Mrs Herbert Fuller (Carrie Constance ...",1st,47.0,female,1,1
"Chambers, Mrs Norman Campbell (Bertha Griggs)","Chambers, Mrs Norman Campbell (Bertha Griggs)",1st,31.0,female,1,1
"Cherry, Miss Gladys","Cherry, Miss Gladys",1st,NaN,female,1,1
"Chibnall (Bowerman), Mrs Edith Martha","Chibnall (Bowerman), Mrs Edith Martha",1st,NaN,female,1,1
"Clark, Mrs Walter Miller (Virginia McDowell)","Clark, Mrs Walter Miller (Virginia McDowell)",1st,26.0,female,1,1
"Compton, Mrs Alexander Taylor (Mary Eliza Ingersoll)","Compton, Mrs Alexander Taylor (Mary Eliza Inge...",1st,64.0,female,1,1
"Compton, Miss Sara Rebecca","Compton, Miss Sara Rebecca",1st,39.0,female,1,1
...,...,...,...,...,...,...
"Salkjelsvik, Miss Anna","Salkjelsvik, Miss Anna",3rd,NaN,female,1,1
"Sandstrom, Miss Hjalmar","Sandstrom, Miss Hjalmar",3rd,NaN,female,1,1
"Sandstrom, Miss Beatrice Irene","Sandstrom, Miss Beatrice Irene",3rd,1.5,female,0,1
"Sandstrom, Miss Marguerite Rut","Sandstrom, Miss Marguerite Rut",3rd,NaN,female,0,1
"Shine, Miss Ellen","Shine, Miss Ellen",3rd,NaN,female,1,1
"Sjoblom, Miss Anna Sofia","Sjoblom, Miss Anna Sofia",3rd,NaN,female,1,1
"Skoog, Miss Mabel","Skoog, Miss Mabel",3rd,NaN,female,0,1
"Skoog, Miss Margit","Skoog, Miss Margit",3rd,NaN,female,0,1
"Skoog, Mrs William","Skoog, Mrs William",3rd,NaN,female,0,1
"Smyth, Miss Julia","Smyth, Miss Julia",3rd,NaN,female,1,1
"Solvang, Mrs Lena Jacobsen","Solvang, Mrs Lena Jacobsen",3rd,NaN,female,0,1
"Stanley, Miss Amy Zilla Elsie","Stanley, Miss Amy Zilla Elsie",3rd,NaN,female,1,1
"Strandberg, Miss Ida Sofia","Strandberg, Miss Ida Sofia",3rd,NaN,female,0,1
"Strom, Mrs Wilhelm","Strom, Mrs Wilhelm",3rd,NaN,female,0,1
"Strom, Miss Telma (Selma) Matilda","Strom, Miss Telma (Selma) Matilda",3rd,NaN,female,0,1
"Thomas, Mrs Alexander","Thomas, Mrs Alexander",3rd,NaN,female,1,1
"Thorneycroft, Mrs Percival","Thorneycroft, Mrs Percival",3rd,NaN,female,1,1
"Touma (Thomas), Mrs Darwin","Touma (Thomas), Mrs Darwin",3rd,NaN,female,0,1
"Touma (Thomas), Miss Hannah","Touma (Thomas), Miss Hannah",3rd,NaN,female,0,1
"Turja, Miss Anna Sofia","Turja, Miss Anna Sofia",3rd,18.0,female,1,1
"Turkula, Mrs Hedvig","Turkula, Mrs Hedvig",3rd,63.0,female,1,1
"Van der Planke, Miss Augusta","Van der Planke, Miss Augusta",3rd,18.0,female,0,1
"Van der Planke, Mrs Jules","Van der Planke, Mrs Jules",3rd,31.0,female,0,1
"Van Impe, Miss Catharine","Van Impe, Miss Catharine",3rd,10.0,female,0,1
"Van Impe, Mrs Jean Baptiste","Van Impe, Mrs Jean Baptiste",3rd,30.0,female,0,1
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.0,female,0,1
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.0,female,1,1
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.0,female,1,1
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1

In [7]:
# multiple conditions
df[(df['Sex'] == 'female') & (df['Age'] >= 65)]

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Crosby, Mrs Edward Gifford (Catherine Elizabeth Halstead)","Crosby, Mrs Edward Gifford (Catherine Elizabet...",1st,69.0,female,1,1

## 3.5 Replacing Values

In [8]:
# replace any instance of 'female' with Woman
df['Sex'].replace('female', 'Woman')

Name
Allen, Miss Elisabeth Walton                        Woman
Allison, Miss Helen Loraine                         Woman
Allison, Mr Hudson Joshua Creighton                  male
Allison, Mrs Hudson JC (Bessie Waldo Daniels)       Woman
Allison, Master Hudson Trevor                        male
Anderson, Mr Harry                                   male
Andrews, Miss Kornelia Theodosia                    Woman
Andrews, Mr Thomas, jr                               male
Appleton, Mrs Edward Dale (Charlotte Lamson)        Woman
Artagaveytia, Mr Ramon                               male
Astor, Colonel John Jacob                            male
Astor, Mrs John Jacob (Madeleine Talmadge Force)    Woman
Aubert, Mrs Leontine Pauline                        Woman
Barkworth, Mr Algernon H                             male
Baumann, Mr John D                                   male
Baxter, Mrs James (Helene DeLaudeniere Chaput)      Woman
Baxter, Mr Quigg Edmond                              male
Beattie, Mr Thomson                                  male
Beckwith, Mr Richard Leonard                         male
Beckwith, Mrs Richard Leonard (Sallie Monypeny)     Woman
Behr, Mr Karl Howell                                 male
Birnbaum, Mr Jakob                                   male
Bishop, Mr Dickinson H                               male
Bishop, Mrs Dickinson H (Helen Walton)              Woman
Bjornstrm-Steffansson, Mr Mauritz Hakan              male
Blackwell, Mr Stephen Weart                          male
Blank, Mr Henry                                      male
Bonnell, Miss Caroline                              Woman
Bonnell, Miss Elizabeth                             Woman
Borebank, Mr John James                              male
                                                    ...
Vestrom, Miss Hulda Amanda Adolfina                 Woman
Vonk, Mr Jenko                                       male
Ware, Mr Frederick                                   male
Warren, Mr Charles William                           male
Wazli, Mr Yousif                                     male
Webber, Mr James                                     male
Wennerstrom, Mr August Edvard                        male
Wenzel, Mr Linhart                                   male
Widegren, Mr Charles Peter                           male
Wiklund, Mr Jacob Alfred                             male
Wilkes, Mrs Ellen                                   Woman
Willer, Mr Aaron                                     male
Willey, Mr Edward                                    male
Williams, Mr Howard Hugh                             male
Williams, Mr Leslie                                  male
Windelov, Mr Einar                                   male
Wirz, Mr Albert                                      male
Wiseman, Mr Phillippe                                male
Wittevrongel, Mr Camiel                              male
Yalsevac, Mr Ivan                                    male
Yasbeck, Mr Antoni                                   male
Yasbeck, Mrs Antoni                                 Woman
Youssef, Mr Gerios                                   male
Zabour, Miss Hileni                                 Woman
Zabour, Miss Tamini                                 Woman
Zakarian, Mr Artun                                   male
Zakarian, Mr Maprieder                               male
Zenni, Mr Philip                                     male
Lievens, Mr Rene                                     male
Zimmerman, Leo                                       male
Name: Sex, Length: 1313, dtype: object

In [9]:
# replace any instance of 'female' with Woman
df['Sex'].replace(['female', 'male'], ['Woman', 'Man'])

Name
Allen, Miss Elisabeth Walton                        Woman
Allison, Miss Helen Loraine                         Woman
Allison, Mr Hudson Joshua Creighton                   Man
Allison, Mrs Hudson JC (Bessie Waldo Daniels)       Woman
Allison, Master Hudson Trevor                         Man
Anderson, Mr Harry                                    Man
Andrews, Miss Kornelia Theodosia                    Woman
Andrews, Mr Thomas, jr                                Man
Appleton, Mrs Edward Dale (Charlotte Lamson)        Woman
Artagaveytia, Mr Ramon                                Man
Astor, Colonel John Jacob                             Man
Astor, Mrs John Jacob (Madeleine Talmadge Force)    Woman
Aubert, Mrs Leontine Pauline                        Woman
Barkworth, Mr Algernon H                              Man
Baumann, Mr John D                                    Man
Baxter, Mrs James (Helene DeLaudeniere Chaput)      Woman
Baxter, Mr Quigg Edmond                               Man
Beattie, Mr Thomson                                   Man
Beckwith, Mr Richard Leonard                          Man
Beckwith, Mrs Richard Leonard (Sallie Monypeny)     Woman
Behr, Mr Karl Howell                                  Man
Birnbaum, Mr Jakob                                    Man
Bishop, Mr Dickinson H                                Man
Bishop, Mrs Dickinson H (Helen Walton)              Woman
Bjornstrm-Steffansson, Mr Mauritz Hakan               Man
Blackwell, Mr Stephen Weart                           Man
Blank, Mr Henry                                       Man
Bonnell, Miss Caroline                              Woman
Bonnell, Miss Elizabeth                             Woman
Borebank, Mr John James                               Man
                                                    ...
Vestrom, Miss Hulda Amanda Adolfina                 Woman
Vonk, Mr Jenko                                        Man
Ware, Mr Frederick                                    Man
Warren, Mr Charles William                            Man
Wazli, Mr Yousif                                      Man
Webber, Mr James                                      Man
Wennerstrom, Mr August Edvard                         Man
Wenzel, Mr Linhart                                    Man
Widegren, Mr Charles Peter                            Man
Wiklund, Mr Jacob Alfred                              Man
Wilkes, Mrs Ellen                                   Woman
Willer, Mr Aaron                                      Man
Willey, Mr Edward                                     Man
Williams, Mr Howard Hugh                              Man
Williams, Mr Leslie                                   Man
Windelov, Mr Einar                                    Man
Wirz, Mr Albert                                       Man
Wiseman, Mr Phillippe                                 Man
Wittevrongel, Mr Camiel                               Man
Yalsevac, Mr Ivan                                     Man
Yasbeck, Mr Antoni                                    Man
Yasbeck, Mrs Antoni                                 Woman
Youssef, Mr Gerios                                    Man
Zabour, Miss Hileni                                 Woman
Zabour, Miss Tamini                                 Woman
Zakarian, Mr Artun                                    Man
Zakarian, Mr Maprieder                                Man
Zenni, Mr Philip                                      Man
Lievens, Mr Rene                                      Man
Zimmerman, Leo                                        Man
Name: Sex, Length: 1313, dtype: object

In [10]:
df.replace(1, "One")

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29,female,One,One
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2,female,0,One
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25,female,0,One
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,One,0
"Anderson, Mr Harry","Anderson, Mr Harry",1st,47,male,One,0
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63,female,One,One
"Andrews, Mr Thomas, jr","Andrews, Mr Thomas, jr",1st,39,male,0,0
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58,female,One,One
"Artagaveytia, Mr Ramon","Artagaveytia, Mr Ramon",1st,71,male,0,0
"Astor, Colonel John Jacob","Astor, Colonel John Jacob",1st,47,male,0,0
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19,female,One,One
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,One,One
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,NaN,male,One,0
"Baumann, Mr John D","Baumann, Mr John D",1st,NaN,male,0,0
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50,female,One,One
"Baxter, Mr Quigg Edmond","Baxter, Mr Quigg Edmond",1st,24,male,0,0
"Beattie, Mr Thomson","Beattie, Mr Thomson",1st,36,male,0,0
"Beckwith, Mr Richard Leonard","Beckwith, Mr Richard Leonard",1st,37,male,One,0
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47,female,One,One
"Behr, Mr Karl Howell","Behr, Mr Karl Howell",1st,26,male,One,0
"Birnbaum, Mr Jakob","Birnbaum, Mr Jakob",1st,25,male,0,0
"Bishop, Mr Dickinson H","Bishop, Mr Dickinson H",1st,25,male,One,0
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19,female,One,One
"Bjornstrm-Steffansson, Mr Mauritz Hakan","Bjornstrm-Steffansson, Mr Mauritz Hakan",1st,28,male,One,0
"Blackwell, Mr Stephen Weart","Blackwell, Mr Stephen Weart",1st,45,male,0,0
"Blank, Mr Henry","Blank, Mr Henry",1st,39,male,One,0
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30,female,One,One
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58,female,One,One
"Borebank, Mr John James","Borebank, Mr John James",1st,NaN,male,0,0
...,...,...,...,...,...,...
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14,female,0,One
"Vonk, Mr Jenko","Vonk, Mr Jenko",3rd,22,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,NaN,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,NaN,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,NaN,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,NaN,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,NaN,male,One,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,NaN,male,0,0
"Widegren, Mr Charles Peter","Widegren, Mr Charles Peter",3rd,51,male,0,0
"Wiklund, Mr Jacob Alfred","Wiklund, Mr Jacob Alfred",3rd,18,male,0,0
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45,female,One,One
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,NaN,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,NaN,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,NaN,male,0,0
"Williams, Mr Leslie","Williams, Mr Leslie",3rd,28,male,0,0
"Windelov, Mr Einar","Windelov, Mr Einar",3rd,21,male,0,0
"Wirz, Mr Albert","Wirz, Mr Albert",3rd,27,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,NaN,male,0,0
"Wittevrongel, Mr Camiel","Wittevrongel, Mr Camiel",3rd,36,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,NaN,male,One,0
"Yasbeck, Mr Antoni","Yasbeck, Mr Antoni",3rd,27,male,0,0
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15,female,One,One
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,NaN,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,One
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,One
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,27,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,26,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,22,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,24,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,29,male,0,0

## 3.6 Renaming Columns

In [12]:
df.rename(columns={'PClass': 'Passenger Class'})

,Name,Passenger Class,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0
"Anderson, Mr Harry","Anderson, Mr Harry",1st,47.00,male,1,0
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
"Andrews, Mr Thomas, jr","Andrews, Mr Thomas, jr",1st,39.00,male,0,0
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1
"Artagaveytia, Mr Ramon","Artagaveytia, Mr Ramon",1st,71.00,male,0,0
"Astor, Colonel John Jacob","Astor, Colonel John Jacob",1st,47.00,male,0,0
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.00,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,NaN,male,1,0
"Baumann, Mr John D","Baumann, Mr John D",1st,NaN,male,0,0
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.00,female,1,1
"Baxter, Mr Quigg Edmond","Baxter, Mr Quigg Edmond",1st,24.00,male,0,0
"Beattie, Mr Thomson","Beattie, Mr Thomson",1st,36.00,male,0,0
"Beckwith, Mr Richard Leonard","Beckwith, Mr Richard Leonard",1st,37.00,male,1,0
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.00,female,1,1
"Behr, Mr Karl Howell","Behr, Mr Karl Howell",1st,26.00,male,1,0
"Birnbaum, Mr Jakob","Birnbaum, Mr Jakob",1st,25.00,male,0,0
"Bishop, Mr Dickinson H","Bishop, Mr Dickinson H",1st,25.00,male,1,0
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.00,female,1,1
"Bjornstrm-Steffansson, Mr Mauritz Hakan","Bjornstrm-Steffansson, Mr Mauritz Hakan",1st,28.00,male,1,0
"Blackwell, Mr Stephen Weart","Blackwell, Mr Stephen Weart",1st,45.00,male,0,0
"Blank, Mr Henry","Blank, Mr Henry",1st,39.00,male,1,0
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.00,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.00,female,1,1
"Borebank, Mr John James","Borebank, Mr John James",1st,NaN,male,0,0
...,...,...,...,...,...,...
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.00,female,0,1
"Vonk, Mr Jenko","Vonk, Mr Jenko",3rd,22.00,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,NaN,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,NaN,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,NaN,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,NaN,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,NaN,male,1,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,NaN,male,0,0
"Widegren, Mr Charles Peter","Widegren, Mr Charles Peter",3rd,51.00,male,0,0
"Wiklund, Mr Jacob Alfred","Wiklund, Mr Jacob Alfred",3rd,18.00,male,0,0
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.00,female,1,1
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,NaN,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,NaN,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,NaN,male,0,0
"Williams, Mr Leslie","Williams, Mr Leslie",3rd,28.00,male,0,0
"Windelov, Mr Einar","Windelov, Mr Einar",3rd,21.00,male,0,0
"Wirz, Mr Albert","Wirz, Mr Albert",3rd,27.00,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,NaN,male,0,0
"Wittevrongel, Mr Camiel","Wittevrongel, Mr Camiel",3rd,36.00,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,NaN,male,1,0
"Yasbeck, Mr Antoni","Yasbeck, Mr Antoni",3rd,27.00,male,0,0
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.00,female,1,1
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,NaN,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,27.00,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,26.00,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,22.00,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,24.00,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,29.00,male,0,0

In [13]:
df.rename(columns={'PClass': 'Passenger Class', 'Sex': 'Gender'})

,Name,Passenger Class,Age,Gender,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0
"Anderson, Mr Harry","Anderson, Mr Harry",1st,47.00,male,1,0
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
"Andrews, Mr Thomas, jr","Andrews, Mr Thomas, jr",1st,39.00,male,0,0
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1
"Artagaveytia, Mr Ramon","Artagaveytia, Mr Ramon",1st,71.00,male,0,0
"Astor, Colonel John Jacob","Astor, Colonel John Jacob",1st,47.00,male,0,0
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.00,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,NaN,male,1,0
"Baumann, Mr John D","Baumann, Mr John D",1st,NaN,male,0,0
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.00,female,1,1
"Baxter, Mr Quigg Edmond","Baxter, Mr Quigg Edmond",1st,24.00,male,0,0
"Beattie, Mr Thomson","Beattie, Mr Thomson",1st,36.00,male,0,0
"Beckwith, Mr Richard Leonard","Beckwith, Mr Richard Leonard",1st,37.00,male,1,0
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.00,female,1,1
"Behr, Mr Karl Howell","Behr, Mr Karl Howell",1st,26.00,male,1,0
"Birnbaum, Mr Jakob","Birnbaum, Mr Jakob",1st,25.00,male,0,0
"Bishop, Mr Dickinson H","Bishop, Mr Dickinson H",1st,25.00,male,1,0
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.00,female,1,1
"Bjornstrm-Steffansson, Mr Mauritz Hakan","Bjornstrm-Steffansson, Mr Mauritz Hakan",1st,28.00,male,1,0
"Blackwell, Mr Stephen Weart","Blackwell, Mr Stephen Weart",1st,45.00,male,0,0
"Blank, Mr Henry","Blank, Mr Henry",1st,39.00,male,1,0
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.00,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.00,female,1,1
"Borebank, Mr John James","Borebank, Mr John James",1st,NaN,male,0,0
...,...,...,...,...,...,...
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.00,female,0,1
"Vonk, Mr Jenko","Vonk, Mr Jenko",3rd,22.00,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,NaN,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,NaN,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,NaN,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,NaN,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,NaN,male,1,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,NaN,male,0,0
"Widegren, Mr Charles Peter","Widegren, Mr Charles Peter",3rd,51.00,male,0,0
"Wiklund, Mr Jacob Alfred","Wiklund, Mr Jacob Alfred",3rd,18.00,male,0,0
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.00,female,1,1
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,NaN,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,NaN,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,NaN,male,0,0
"Williams, Mr Leslie","Williams, Mr Leslie",3rd,28.00,male,0,0
"Windelov, Mr Einar","Windelov, Mr Einar",3rd,21.00,male,0,0
"Wirz, Mr Albert","Wirz, Mr Albert",3rd,27.00,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,NaN,male,0,0
"Wittevrongel, Mr Camiel","Wittevrongel, Mr Camiel",3rd,36.00,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,NaN,male,1,0
"Yasbeck, Mr Antoni","Yasbeck, Mr Antoni",3rd,27.00,male,0,0
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.00,female,1,1
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,NaN,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,27.00,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,26.00,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,22.00,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,24.00,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,29.00,male,0,0

## 3.7 Finding the Min, Max, Sum, Average, and Count

In [45]:
print('Maximum: {}'.format(df['Age'].max()))
print('Minimum: {}'.format(df['Age'].min()))
print('Mean: {}'.format(df['Age'].mean()))
print('Sum: {}'.format(df['Age'].sum()))
print('Count: {}'.format(df['Age'].count()))

len(df['Age'].isnull())

import numpy as np
df[df['Age']!=np.nan]

len(df[df['Age']!=np.nan])

Maximum: 71.0
Minimum: 0.17
Mean: 30.397989417989415
Sum: 22980.879999999997
Count: 756

1313

In [15]:
print("Variance: {}".format(df.var()))
print("Standard Deviation: {}".format(df.std()))
print("Kurtosis: {}".format(df.kurt()))
print("Skewness: {}".format(df.skew()))

Variance: Age         203.320470
Survived      0.225437
SexCode       0.228230
dtype: float64
Standard Deviation: Age         14.259049
Survived     0.474802
SexCode      0.477734
dtype: float64
Kurtosis: Age        -0.036536
Survived   -1.562162
SexCode    -1.616702
dtype: float64
Skewness: Age         0.368511
Survived    0.663491
SexCode     0.621098
dtype: float64

## 3.8 Finding Unique Values

In [16]:
df['Sex'].unique()

array(['female', 'male'], dtype=object)

In [17]:
# value_counts will display all unique values with the number of times each value appears
df['Sex'].value_counts()

male      851
female    462
Name: Sex, dtype: int64

## 3.9 Handling Missing Values

In [18]:
# select missing values, show 2 rows
df[df['Age'].isnull()]

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,NaN,male,1,0
"Baumann, Mr John D","Baumann, Mr John D",1st,NaN,male,0,0
"Borebank, Mr John James","Borebank, Mr John James",1st,NaN,male,0,0
"Bradley, Mr George","Bradley, Mr George",1st,NaN,male,1,0
"Brewe, Dr Arthur Jackson","Brewe, Dr Arthur Jackson",1st,NaN,male,0,0
"Calderhead, Mr Edward P","Calderhead, Mr Edward P",1st,NaN,male,1,0
"Carrau, Mr Francisco M","Carrau, Mr Francisco M",1st,NaN,male,0,0
"Carrau, Mr Jose Pedro","Carrau, Mr Jose Pedro",1st,NaN,male,0,0
"Cassebeer, Mrs Henry Arthur jr (Genevieve Fosdick)","Cassebeer, Mrs Henry Arthur jr (Genevieve Fosd...",1st,NaN,female,1,1
"Cavendish, Mrs Tyrell William Julia Florence Siegel","Cavendish, Mrs Tyrell William Julia Florence S...",1st,NaN,female,1,1
"Cherry, Miss Gladys","Cherry, Miss Gladys",1st,NaN,female,1,1
"Chevre, Mr Paul","Chevre, Mr Paul",1st,NaN,male,1,0
"Chibnall (Bowerman), Mrs Edith Martha","Chibnall (Bowerman), Mrs Edith Martha",1st,NaN,female,1,1
"Chisholm, Mr Roderick Robert","Chisholm, Mr Roderick Robert",1st,NaN,male,0,0
"Clifford, Mr George Quincy","Clifford, Mr George Quincy",1st,NaN,male,0,0
"Colley, Mr Edward Pomeroy","Colley, Mr Edward Pomeroy",1st,NaN,male,0,0
"Crafton, Mr John Bertram","Crafton, Mr John Bertram",1st,NaN,male,0,0
"Daly, Mr Peter Denis","Daly, Mr Peter Denis",1st,NaN,male,1,0
"de Villiers, Madame Berthe","de Villiers, Madame Berthe",1st,NaN,female,1,1
"Dodge, Dr Washington","Dodge, Dr Washington",1st,NaN,male,1,0
"Dodge, Mrs Washington (Ruth Vidaver)","Dodge, Mrs Washington (Ruth Vidaver)",1st,NaN,female,1,1
"Flegenheim, Mrs Alfred (Antoinette)","Flegenheim, Mrs Alfred (Antoinette)",1st,NaN,female,1,1
"Flynn, Mr John Irving","Flynn, Mr John Irving",1st,NaN,male,1,0
"Franklin, Mr Thomas Parham","Franklin, Mr Thomas Parham",1st,NaN,male,0,0
"Frauenthal, Mrs Henry William (Clara Heinsheimer)","Frauenthal, Mrs Henry William (Clara Heinsheimer)",1st,NaN,female,1,1
"Goldenberg, Mrs Samuel L (Edwiga Grabowsko)","Goldenberg, Mrs Samuel L (Edwiga Grabowsko)",1st,NaN,female,1,1
"Hawksford, Mr Walter James","Hawksford, Mr Walter James",1st,NaN,male,1,0
"Head, Mr Christopher","Head, Mr Christopher",1st,NaN,male,0,0
"Hilliard, Mr Herbert Henry","Hilliard, Mr Herbert Henry",1st,NaN,male,0,0
...,...,...,...,...,...,...
"Thorneycroft, Mrs Percival","Thorneycroft, Mrs Percival",3rd,NaN,female,1,1
"Tikkanen, Mr Juho","Tikkanen, Mr Juho",3rd,NaN,male,0,0
"Tobin, Mr Roger","Tobin, Mr Roger",3rd,NaN,male,0,0
"Todoroff, Mr Lalio","Todoroff, Mr Lalio",3rd,NaN,male,0,0
"Toerber, Mr Ernest William","Toerber, Mr Ernest William",3rd,NaN,male,0,0
"Tomlin, Mr Ernest Portage","Tomlin, Mr Ernest Portage",3rd,NaN,male,0,0
"Torfa, Mr Assad","Torfa, Mr Assad",3rd,NaN,male,0,0
"Touma (Thomas), Mrs Darwin","Touma (Thomas), Mrs Darwin",3rd,NaN,female,0,1
"Touma (Thomas), Master George","Touma (Thomas), Master George",3rd,NaN,male,0,0
"Touma (Thomas), Miss Hannah","Touma (Thomas), Miss Hannah",3rd,NaN,female,0,1
"Turcin, Mr Stefan","Turcin, Mr Stefan",3rd,NaN,male,0,0
"Uzelas, Mr Joso","Uzelas, Mr Joso",3rd,NaN,male,0,0
"Van Billiard, Mr Austin Blyler","Van Billiard, Mr Austin Blyler",3rd,NaN,male,0,0
"Van Billiard, Master James William","Van Billiard, Master James William",3rd,NaN,male,0,0
"Van Billiard, Master Walter John","Van Billiard, Master Walter John",3rd,NaN,male,0,0
"Vassilios, Mr Catavelas","Vassilios, Mr Catavelas",3rd,NaN,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,NaN,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,NaN,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,NaN,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,NaN,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,NaN,male,1,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,NaN,male,0,0
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,NaN,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,NaN,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,NaN,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,NaN,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,NaN,male,1,0
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,NaN,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1

## 3.10 Deleting a Column

In [19]:

# axis=1 means the column axis
df.drop('Age', axis=1)

,Name,PClass,Sex,Survived,SexCode
Name,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,male,1,0
"Anderson, Mr Harry","Anderson, Mr Harry",1st,male,1,0
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,female,1,1
"Andrews, Mr Thomas, jr","Andrews, Mr Thomas, jr",1st,male,0,0
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,female,1,1
"Artagaveytia, Mr Ramon","Artagaveytia, Mr Ramon",1st,male,0,0
"Astor, Colonel John Jacob","Astor, Colonel John Jacob",1st,male,0,0
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,female,1,1
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,male,1,0
"Baumann, Mr John D","Baumann, Mr John D",1st,male,0,0
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,female,1,1
"Baxter, Mr Quigg Edmond","Baxter, Mr Quigg Edmond",1st,male,0,0
"Beattie, Mr Thomson","Beattie, Mr Thomson",1st,male,0,0
"Beckwith, Mr Richard Leonard","Beckwith, Mr Richard Leonard",1st,male,1,0
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,female,1,1
"Behr, Mr Karl Howell","Behr, Mr Karl Howell",1st,male,1,0
"Birnbaum, Mr Jakob","Birnbaum, Mr Jakob",1st,male,0,0
"Bishop, Mr Dickinson H","Bishop, Mr Dickinson H",1st,male,1,0
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,female,1,1
"Bjornstrm-Steffansson, Mr Mauritz Hakan","Bjornstrm-Steffansson, Mr Mauritz Hakan",1st,male,1,0
"Blackwell, Mr Stephen Weart","Blackwell, Mr Stephen Weart",1st,male,0,0
"Blank, Mr Henry","Blank, Mr Henry",1st,male,1,0
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,female,1,1
"Borebank, Mr John James","Borebank, Mr John James",1st,male,0,0
...,...,...,...,...,...
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,female,0,1
"Vonk, Mr Jenko","Vonk, Mr Jenko",3rd,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,male,1,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,male,0,0
"Widegren, Mr Charles Peter","Widegren, Mr Charles Peter",3rd,male,0,0
"Wiklund, Mr Jacob Alfred","Wiklund, Mr Jacob Alfred",3rd,male,0,0
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,female,1,1
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,male,0,0
"Williams, Mr Leslie","Williams, Mr Leslie",3rd,male,0,0
"Windelov, Mr Einar","Windelov, Mr Einar",3rd,male,0,0
"Wirz, Mr Albert","Wirz, Mr Albert",3rd,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,male,0,0
"Wittevrongel, Mr Camiel","Wittevrongel, Mr Camiel",3rd,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,male,1,0
"Yasbeck, Mr Antoni","Yasbeck, Mr Antoni",3rd,male,0,0
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,female,1,1
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,female,0,1
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,male,0,0

## 3.11 Deleting a Row

In [20]:

# create new dataframe excluding the rows you want to delete
df[df['Sex'] != 'male']

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.0,female,0,1
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.0,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.0,female,1,1
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.0,female,1,1
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.0,female,1,1
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.0,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.0,female,1,1
"Bowen, Miss Grace Scott","Bowen, Miss Grace Scott",1st,45.0,female,1,1
"Bowerman, Miss Elsie Edith","Bowerman, Miss Elsie Edith",1st,22.0,female,1,1
"Brown, Mrs James Joseph (Margaret Molly"" Tobin)""","Brown, Mrs James Joseph (Margaret Molly"" Tobin)""",1st,44.0,female,1,1
"Brown, Mrs John Murray (Caroline Lane Lamson)","Brown, Mrs John Murray (Caroline Lane Lamson)",1st,59.0,female,1,1
"Bucknell, Mrs William Robert (Emma Eliza Ward)","Bucknell, Mrs William Robert (Emma Eliza Ward)",1st,60.0,female,1,1
"Candee, Mrs Edward (Helen Churchill Hungerford)","Candee, Mrs Edward (Helen Churchill Hungerford)",1st,53.0,female,1,1
"Cardeza, Mrs James Warburton Martinez (Charlotte Wardle Drake)","Cardeza, Mrs James Warburton Martinez (Charlot...",1st,58.0,female,1,1
"Carter, Mrs William Ernest (Lucile Polk)","Carter, Mrs William Ernest (Lucile Polk)",1st,36.0,female,1,1
"Carter, Miss Lucile Polk","Carter, Miss Lucile Polk",1st,14.0,female,1,1
"Cassebeer, Mrs Henry Arthur jr (Genevieve Fosdick)","Cassebeer, Mrs Henry Arthur jr (Genevieve Fosd...",1st,NaN,female,1,1
"Cavendish, Mrs Tyrell William Julia Florence Siegel","Cavendish, Mrs Tyrell William Julia Florence S...",1st,NaN,female,1,1
"Chaffee, Mrs Herbert Fuller (Carrie Constance Toogood)","Chaffee, Mrs Herbert Fuller (Carrie Constance ...",1st,47.0,female,1,1
"Chambers, Mrs Norman Campbell (Bertha Griggs)","Chambers, Mrs Norman Campbell (Bertha Griggs)",1st,31.0,female,1,1
"Cherry, Miss Gladys","Cherry, Miss Gladys",1st,NaN,female,1,1
"Chibnall (Bowerman), Mrs Edith Martha","Chibnall (Bowerman), Mrs Edith Martha",1st,NaN,female,1,1
"Clark, Mrs Walter Miller (Virginia McDowell)","Clark, Mrs Walter Miller (Virginia McDowell)",1st,26.0,female,1,1
"Compton, Mrs Alexander Taylor (Mary Eliza Ingersoll)","Compton, Mrs Alexander Taylor (Mary Eliza Inge...",1st,64.0,female,1,1
"Compton, Miss Sara Rebecca","Compton, Miss Sara Rebecca",1st,39.0,female,1,1
...,...,...,...,...,...,...
"Salkjelsvik, Miss Anna","Salkjelsvik, Miss Anna",3rd,NaN,female,1,1
"Sandstrom, Miss Hjalmar","Sandstrom, Miss Hjalmar",3rd,NaN,female,1,1
"Sandstrom, Miss Beatrice Irene","Sandstrom, Miss Beatrice Irene",3rd,1.5,female,0,1
"Sandstrom, Miss Marguerite Rut","Sandstrom, Miss Marguerite Rut",3rd,NaN,female,0,1
"Shine, Miss Ellen","Shine, Miss Ellen",3rd,NaN,female,1,1
"Sjoblom, Miss Anna Sofia","Sjoblom, Miss Anna Sofia",3rd,NaN,female,1,1
"Skoog, Miss Mabel","Skoog, Miss Mabel",3rd,NaN,female,0,1
"Skoog, Miss Margit","Skoog, Miss Margit",3rd,NaN,female,0,1
"Skoog, Mrs William","Skoog, Mrs William",3rd,NaN,female,0,1
"Smyth, Miss Julia","Smyth, Miss Julia",3rd,NaN,female,1,1
"Solvang, Mrs Lena Jacobsen","Solvang, Mrs Lena Jacobsen",3rd,NaN,female,0,1
"Stanley, Miss Amy Zilla Elsie","Stanley, Miss Amy Zilla Elsie",3rd,NaN,female,1,1
"Strandberg, Miss Ida Sofia","Strandberg, Miss Ida Sofia",3rd,NaN,female,0,1
"Strom, Mrs Wilhelm","Strom, Mrs Wilhelm",3rd,NaN,female,0,1
"Strom, Miss Telma (Selma) Matilda","Strom, Miss Telma (Selma) Matilda",3rd,NaN,female,0,1
"Thomas, Mrs Alexander","Thomas, Mrs Alexander",3rd,NaN,female,1,1
"Thorneycroft, Mrs Percival","Thorneycroft, Mrs Percival",3rd,NaN,female,1,1
"Touma (Thomas), Mrs Darwin","Touma (Thomas), Mrs Darwin",3rd,NaN,female,0,1
"Touma (Thomas), Miss Hannah","Touma (Thomas), Miss Hannah",3rd,NaN,female,0,1
"Turja, Miss Anna Sofia","Turja, Miss Anna Sofia",3rd,18.0,female,1,1
"Turkula, Mrs Hedvig","Turkula, Mrs Hedvig",3rd,63.0,female,1,1
"Van der Planke, Miss Augusta","Van der Planke, Miss Augusta",3rd,18.0,female,0,1
"Van der Planke, Mrs Jules","Van der Planke, Mrs Jules",3rd,31.0,female,0,1
"Van Impe, Miss Catharine","Van Impe, Miss Catharine",3rd,10.0,female,0,1
"Van Impe, Mrs Jean Baptiste","Van Impe, Mrs Jean Baptiste",3rd,30.0,female,0,1
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.0,female,0,1
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.0,female,1,1
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.0,female,1,1
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1

In [22]:

# create new dataframe excluding the rows you want to delete
df[df['Sex'] != 'male']

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.0,female,0,1
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.0,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.0,female,1,1
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.0,female,1,1
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.0,female,1,1
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.0,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.0,female,1,1
"Bowen, Miss Grace Scott","Bowen, Miss Grace Scott",1st,45.0,female,1,1
"Bowerman, Miss Elsie Edith","Bowerman, Miss Elsie Edith",1st,22.0,female,1,1
"Brown, Mrs James Joseph (Margaret Molly"" Tobin)""","Brown, Mrs James Joseph (Margaret Molly"" Tobin)""",1st,44.0,female,1,1
"Brown, Mrs John Murray (Caroline Lane Lamson)","Brown, Mrs John Murray (Caroline Lane Lamson)",1st,59.0,female,1,1
"Bucknell, Mrs William Robert (Emma Eliza Ward)","Bucknell, Mrs William Robert (Emma Eliza Ward)",1st,60.0,female,1,1
"Candee, Mrs Edward (Helen Churchill Hungerford)","Candee, Mrs Edward (Helen Churchill Hungerford)",1st,53.0,female,1,1
"Cardeza, Mrs James Warburton Martinez (Charlotte Wardle Drake)","Cardeza, Mrs James Warburton Martinez (Charlot...",1st,58.0,female,1,1
"Carter, Mrs William Ernest (Lucile Polk)","Carter, Mrs William Ernest (Lucile Polk)",1st,36.0,female,1,1
"Carter, Miss Lucile Polk","Carter, Miss Lucile Polk",1st,14.0,female,1,1
"Cassebeer, Mrs Henry Arthur jr (Genevieve Fosdick)","Cassebeer, Mrs Henry Arthur jr (Genevieve Fosd...",1st,NaN,female,1,1
"Cavendish, Mrs Tyrell William Julia Florence Siegel","Cavendish, Mrs Tyrell William Julia Florence S...",1st,NaN,female,1,1
"Chaffee, Mrs Herbert Fuller (Carrie Constance Toogood)","Chaffee, Mrs Herbert Fuller (Carrie Constance ...",1st,47.0,female,1,1
"Chambers, Mrs Norman Campbell (Bertha Griggs)","Chambers, Mrs Norman Campbell (Bertha Griggs)",1st,31.0,female,1,1
"Cherry, Miss Gladys","Cherry, Miss Gladys",1st,NaN,female,1,1
"Chibnall (Bowerman), Mrs Edith Martha","Chibnall (Bowerman), Mrs Edith Martha",1st,NaN,female,1,1
"Clark, Mrs Walter Miller (Virginia McDowell)","Clark, Mrs Walter Miller (Virginia McDowell)",1st,26.0,female,1,1
"Compton, Mrs Alexander Taylor (Mary Eliza Ingersoll)","Compton, Mrs Alexander Taylor (Mary Eliza Inge...",1st,64.0,female,1,1
"Compton, Miss Sara Rebecca","Compton, Miss Sara Rebecca",1st,39.0,female,1,1
...,...,...,...,...,...,...
"Salkjelsvik, Miss Anna","Salkjelsvik, Miss Anna",3rd,NaN,female,1,1
"Sandstrom, Miss Hjalmar","Sandstrom, Miss Hjalmar",3rd,NaN,female,1,1
"Sandstrom, Miss Beatrice Irene","Sandstrom, Miss Beatrice Irene",3rd,1.5,female,0,1
"Sandstrom, Miss Marguerite Rut","Sandstrom, Miss Marguerite Rut",3rd,NaN,female,0,1
"Shine, Miss Ellen","Shine, Miss Ellen",3rd,NaN,female,1,1
"Sjoblom, Miss Anna Sofia","Sjoblom, Miss Anna Sofia",3rd,NaN,female,1,1
"Skoog, Miss Mabel","Skoog, Miss Mabel",3rd,NaN,female,0,1
"Skoog, Miss Margit","Skoog, Miss Margit",3rd,NaN,female,0,1
"Skoog, Mrs William","Skoog, Mrs William",3rd,NaN,female,0,1
"Smyth, Miss Julia","Smyth, Miss Julia",3rd,NaN,female,1,1
"Solvang, Mrs Lena Jacobsen","Solvang, Mrs Lena Jacobsen",3rd,NaN,female,0,1
"Stanley, Miss Amy Zilla Elsie","Stanley, Miss Amy Zilla Elsie",3rd,NaN,female,1,1
"Strandberg, Miss Ida Sofia","Strandberg, Miss Ida Sofia",3rd,NaN,female,0,1
"Strom, Mrs Wilhelm","Strom, Mrs Wilhelm",3rd,NaN,female,0,1
"Strom, Miss Telma (Selma) Matilda","Strom, Miss Telma (Selma) Matilda",3rd,NaN,female,0,1
"Thomas, Mrs Alexander","Thomas, Mrs Alexander",3rd,NaN,female,1,1
"Thorneycroft, Mrs Percival","Thorneycroft, Mrs Percival",3rd,NaN,female,1,1
"Touma (Thomas), Mrs Darwin","Touma (Thomas), Mrs Darwin",3rd,NaN,female,0,1
"Touma (Thomas), Miss Hannah","Touma (Thomas), Miss Hannah",3rd,NaN,female,0,1
"Turja, Miss Anna Sofia","Turja, Miss Anna Sofia",3rd,18.0,female,1,1
"Turkula, Mrs Hedvig","Turkula, Mrs Hedvig",3rd,63.0,female,1,1
"Van der Planke, Miss Augusta","Van der Planke, Miss Augusta",3rd,18.0,female,0,1
"Van der Planke, Mrs Jules","Van der Planke, Mrs Jules",3rd,31.0,female,0,1
"Van Impe, Miss Catharine","Van Impe, Miss Catharine",3rd,10.0,female,0,1
"Van Impe, Mrs Jean Baptiste","Van Impe, Mrs Jean Baptiste",3rd,30.0,female,0,1
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.0,female,0,1
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.0,female,1,1
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.0,female,1,1
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1

In [24]:
# delete a row by index
df[df.index != 0]

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0
"Anderson, Mr Harry","Anderson, Mr Harry",1st,47.00,male,1,0
"Andrews, Miss Kornelia Theodosia","Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
"Andrews, Mr Thomas, jr","Andrews, Mr Thomas, jr",1st,39.00,male,0,0
"Appleton, Mrs Edward Dale (Charlotte Lamson)","Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1
"Artagaveytia, Mr Ramon","Artagaveytia, Mr Ramon",1st,71.00,male,0,0
"Astor, Colonel John Jacob","Astor, Colonel John Jacob",1st,47.00,male,0,0
"Astor, Mrs John Jacob (Madeleine Talmadge Force)","Astor, Mrs John Jacob (Madeleine Talmadge Force)",1st,19.00,female,1,1
"Aubert, Mrs Leontine Pauline","Aubert, Mrs Leontine Pauline",1st,NaN,female,1,1
"Barkworth, Mr Algernon H","Barkworth, Mr Algernon H",1st,NaN,male,1,0
"Baumann, Mr John D","Baumann, Mr John D",1st,NaN,male,0,0
"Baxter, Mrs James (Helene DeLaudeniere Chaput)","Baxter, Mrs James (Helene DeLaudeniere Chaput)",1st,50.00,female,1,1
"Baxter, Mr Quigg Edmond","Baxter, Mr Quigg Edmond",1st,24.00,male,0,0
"Beattie, Mr Thomson","Beattie, Mr Thomson",1st,36.00,male,0,0
"Beckwith, Mr Richard Leonard","Beckwith, Mr Richard Leonard",1st,37.00,male,1,0
"Beckwith, Mrs Richard Leonard (Sallie Monypeny)","Beckwith, Mrs Richard Leonard (Sallie Monypeny)",1st,47.00,female,1,1
"Behr, Mr Karl Howell","Behr, Mr Karl Howell",1st,26.00,male,1,0
"Birnbaum, Mr Jakob","Birnbaum, Mr Jakob",1st,25.00,male,0,0
"Bishop, Mr Dickinson H","Bishop, Mr Dickinson H",1st,25.00,male,1,0
"Bishop, Mrs Dickinson H (Helen Walton)","Bishop, Mrs Dickinson H (Helen Walton)",1st,19.00,female,1,1
"Bjornstrm-Steffansson, Mr Mauritz Hakan","Bjornstrm-Steffansson, Mr Mauritz Hakan",1st,28.00,male,1,0
"Blackwell, Mr Stephen Weart","Blackwell, Mr Stephen Weart",1st,45.00,male,0,0
"Blank, Mr Henry","Blank, Mr Henry",1st,39.00,male,1,0
"Bonnell, Miss Caroline","Bonnell, Miss Caroline",1st,30.00,female,1,1
"Bonnell, Miss Elizabeth","Bonnell, Miss Elizabeth",1st,58.00,female,1,1
"Borebank, Mr John James","Borebank, Mr John James",1st,NaN,male,0,0
...,...,...,...,...,...,...
"Vestrom, Miss Hulda Amanda Adolfina","Vestrom, Miss Hulda Amanda Adolfina",3rd,14.00,female,0,1
"Vonk, Mr Jenko","Vonk, Mr Jenko",3rd,22.00,male,0,0
"Ware, Mr Frederick","Ware, Mr Frederick",3rd,NaN,male,0,0
"Warren, Mr Charles William","Warren, Mr Charles William",3rd,NaN,male,0,0
"Wazli, Mr Yousif","Wazli, Mr Yousif",3rd,NaN,male,0,0
"Webber, Mr James","Webber, Mr James",3rd,NaN,male,0,0
"Wennerstrom, Mr August Edvard","Wennerstrom, Mr August Edvard",3rd,NaN,male,1,0
"Wenzel, Mr Linhart","Wenzel, Mr Linhart",3rd,NaN,male,0,0
"Widegren, Mr Charles Peter","Widegren, Mr Charles Peter",3rd,51.00,male,0,0
"Wiklund, Mr Jacob Alfred","Wiklund, Mr Jacob Alfred",3rd,18.00,male,0,0
"Wilkes, Mrs Ellen","Wilkes, Mrs Ellen",3rd,45.00,female,1,1
"Willer, Mr Aaron","Willer, Mr Aaron",3rd,NaN,male,0,0
"Willey, Mr Edward","Willey, Mr Edward",3rd,NaN,male,0,0
"Williams, Mr Howard Hugh","Williams, Mr Howard Hugh",3rd,NaN,male,0,0
"Williams, Mr Leslie","Williams, Mr Leslie",3rd,28.00,male,0,0
"Windelov, Mr Einar","Windelov, Mr Einar",3rd,21.00,male,0,0
"Wirz, Mr Albert","Wirz, Mr Albert",3rd,27.00,male,0,0
"Wiseman, Mr Phillippe","Wiseman, Mr Phillippe",3rd,NaN,male,0,0
"Wittevrongel, Mr Camiel","Wittevrongel, Mr Camiel",3rd,36.00,male,0,0
"Yalsevac, Mr Ivan","Yalsevac, Mr Ivan",3rd,NaN,male,1,0
"Yasbeck, Mr Antoni","Yasbeck, Mr Antoni",3rd,27.00,male,0,0
"Yasbeck, Mrs Antoni","Yasbeck, Mrs Antoni",3rd,15.00,female,1,1
"Youssef, Mr Gerios","Youssef, Mr Gerios",3rd,NaN,male,0,0
"Zabour, Miss Hileni","Zabour, Miss Hileni",3rd,NaN,female,0,1
"Zabour, Miss Tamini","Zabour, Miss Tamini",3rd,NaN,female,0,1
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,27.00,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,26.00,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,22.00,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,24.00,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,29.00,male,0,0

## 3.13 Grouping Rows by Values

In [25]:
df.groupby('Sex').mean()

              Age  Survived  SexCode
Sex
female  29.396424  0.666667      1.0
male    31.014338  0.166863      0.0

In [26]:
df.groupby('Survived')['Name'].count()

Survived
0    863
1    450
Name: Name, dtype: int64

In [27]:
df.groupby(['Sex', 'Survived'])['Age'].mean()

Sex     Survived
female  0           24.901408
        1           30.867143
male    0           32.320780
        1           25.951875
Name: Age, dtype: float64

## 3.14 Grouping Rows by Time

## 3.15 Looping Over a Column

In [29]:
# for .. in .. loop
for name in df['Name'][0:2]:
    print(name.upper())

ALLEN, MISS ELISABETH WALTON
ALLISON, MISS HELEN LORAINE

In [30]:
# list comprehension (more "pythonic")
[name.upper() for name in df['Name'][0:2]]

['ALLEN, MISS ELISABETH WALTON', 'ALLISON, MISS HELEN LORAINE']

## 3.16 Applying a Function Over All Elements in a Column

In [31]:

def uppercase(x):
    return x.upper()

df['Name'].apply(uppercase)

Name
Allen, Miss Elisabeth Walton                                            ALLEN, MISS ELISABETH WALTON
Allison, Miss Helen Loraine                                              ALLISON, MISS HELEN LORAINE
Allison, Mr Hudson Joshua Creighton                              ALLISON, MR HUDSON JOSHUA CREIGHTON
Allison, Mrs Hudson JC (Bessie Waldo Daniels)          ALLISON, MRS HUDSON JC (BESSIE WALDO DANIELS)
Allison, Master Hudson Trevor                                          ALLISON, MASTER HUDSON TREVOR
Anderson, Mr Harry                                                                ANDERSON, MR HARRY
Andrews, Miss Kornelia Theodosia                                    ANDREWS, MISS KORNELIA THEODOSIA
Andrews, Mr Thomas, jr                                                        ANDREWS, MR THOMAS, JR
Appleton, Mrs Edward Dale (Charlotte Lamson)            APPLETON, MRS EDWARD DALE (CHARLOTTE LAMSON)
Artagaveytia, Mr Ramon                                                        ARTAGAVEYTIA, MR RAMON
Astor, Colonel John Jacob                                                  ASTOR, COLONEL JOHN JACOB
Astor, Mrs John Jacob (Madeleine Talmadge Force)    ASTOR, MRS JOHN JACOB (MADELEINE TALMADGE FORCE)
Aubert, Mrs Leontine Pauline                                            AUBERT, MRS LEONTINE PAULINE
Barkworth, Mr Algernon H                                                    BARKWORTH, MR ALGERNON H
Baumann, Mr John D                                                                BAUMANN, MR JOHN D
Baxter, Mrs James (Helene DeLaudeniere Chaput)        BAXTER, MRS JAMES (HELENE DELAUDENIERE CHAPUT)
Baxter, Mr Quigg Edmond                                                      BAXTER, MR QUIGG EDMOND
Beattie, Mr Thomson                                                              BEATTIE, MR THOMSON
Beckwith, Mr Richard Leonard                                            BECKWITH, MR RICHARD LEONARD
Beckwith, Mrs Richard Leonard (Sallie Monypeny)      BECKWITH, MRS RICHARD LEONARD (SALLIE MONYPENY)
Behr, Mr Karl Howell                                                            BEHR, MR KARL HOWELL
Birnbaum, Mr Jakob                                                                BIRNBAUM, MR JAKOB
Bishop, Mr Dickinson H                                                        BISHOP, MR DICKINSON H
Bishop, Mrs Dickinson H (Helen Walton)                        BISHOP, MRS DICKINSON H (HELEN WALTON)
Bjornstrm-Steffansson, Mr Mauritz Hakan                      BJORNSTRM-STEFFANSSON, MR MAURITZ HAKAN
Blackwell, Mr Stephen Weart                                              BLACKWELL, MR STEPHEN WEART
Blank, Mr Henry                                                                      BLANK, MR HENRY
Bonnell, Miss Caroline                                                        BONNELL, MISS CAROLINE
Bonnell, Miss Elizabeth                                                      BONNELL, MISS ELIZABETH
Borebank, Mr John James                                                      BOREBANK, MR JOHN JAMES
                                                                          ...
Vestrom, Miss Hulda Amanda Adolfina                              VESTROM, MISS HULDA AMANDA ADOLFINA
Vonk, Mr Jenko                                                                        VONK, MR JENKO
Ware, Mr Frederick                                                                WARE, MR FREDERICK
Warren, Mr Charles William                                                WARREN, MR CHARLES WILLIAM
Wazli, Mr Yousif                                                                    WAZLI, MR YOUSIF
Webber, Mr James                                                                    WEBBER, MR JAMES
Wennerstrom, Mr August Edvard                                          WENNERSTROM, MR AUGUST EDVARD
Wenzel, Mr Linhart                                                                WENZEL, MR LINHART
Widegren, Mr Charles Peter                                                WIDEGREN, MR CHARLES PETER
Wiklund, Mr Jacob Alfred                                                    WIKLUND, MR JACOB ALFRED
Wilkes, Mrs Ellen                                                                  WILKES, MRS ELLEN
Willer, Mr Aaron                                                                    WILLER, MR AARON
Willey, Mr Edward                                                                  WILLEY, MR EDWARD
Williams, Mr Howard Hugh                                                    WILLIAMS, MR HOWARD HUGH
Williams, Mr Leslie                                                              WILLIAMS, MR LESLIE
Windelov, Mr Einar                                                                WINDELOV, MR EINAR
Wirz, Mr Albert                                                                      WIRZ, MR ALBERT
Wiseman, Mr Phillippe                                                          WISEMAN, MR PHILLIPPE
Wittevrongel, Mr Camiel                                                      WITTEVRONGEL, MR CAMIEL
Yalsevac, Mr Ivan                                                                  YALSEVAC, MR IVAN
Yasbeck, Mr Antoni                                                                YASBECK, MR ANTONI
Yasbeck, Mrs Antoni                                                              YASBECK, MRS ANTONI
Youssef, Mr Gerios                                                                YOUSSEF, MR GERIOS
Zabour, Miss Hileni                                                              ZABOUR, MISS HILENI
Zabour, Miss Tamini                                                              ZABOUR, MISS TAMINI
Zakarian, Mr Artun                                                                ZAKARIAN, MR ARTUN
Zakarian, Mr Maprieder                                                        ZAKARIAN, MR MAPRIEDER
Zenni, Mr Philip                                                                    ZENNI, MR PHILIP
Lievens, Mr Rene                                                                    LIEVENS, MR RENE
Zimmerman, Leo                                                                        ZIMMERMAN, LEO
Name: Name, Length: 1313, dtype: object

## 3.17 Applying a Function to Groups

In [33]:
df.groupby('Sex').apply(lambda x: x.count())

        Name  PClass  Age  Sex  Survived  SexCode
Sex
female   462     462  288  462       462      462
male     851     851  468  851       851      851